Dating/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'Dating'

urlpatterns = [
    path('selectgender/',GenderselectView.as_view(),name='selectgender'),
    path('gridview/',Gridview.as_view(),name='gridview'),
    path('locationgridview/',LocationGridview.as_view(),name='locationgridview'),
    path('educationgridview/',EducationGridview.as_view(),name='educationgridview'),
    path('gallery/',GalleryView.as_view(),name='gallery'),
    path('gallery/delete/<int:pk>/', MediaDeleteView.as_view(), name='media_delete'),
    path('user_detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
    path('send_request/<int:user_id>/', SendrequestView.as_view(), name='send_request'),
    path('send_html/', SendhtmlView.as_view(), name='send_html'),
    path('send_html/send_remove/<int:user_id>/', RemovelistView.as_view(), name='send_remove'),
    path('accept_requests/', Accepthtmlview.as_view(), name='accept_requests'),
    path('accept_requests/accept_request/<int:request_id>/', AcceptRequestView.as_view(), name='accept_request'),
    path('accept_requests/reject_request/<int:request_id>/', RejectRequestView.as_view(), name='reject_request'),
    path('friends_list/', FriendsListView.as_view(), name='friends_list'),
    path('short_list/<int:request_id>/', ShortlistView.as_view(), name='short_list'),
    path('short_html/', ShorthtmlView.as_view(), name='short_html'),
    path('not_interest/<int:request_id>/', NotinterestedView.as_view(), name='not_interest'),
    path('send_message/<int:id>/', SendMessageView.as_view(), name='send_message'),    
   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'account'

urlpatterns = [
    path('',index, name='index'),
    path('send_otp/', send_otp, name='send_otp'),
    path('verify_otp/', verify_otp, name='verify_otp'),
    # path('logina/', RegisterLogin.as_view(), name='logina'),
    path('register/',RegisterView.as_view(), name='register'),
    path('employeeinfo/',EmployeeinfoView.as_view(), name='employeeinfo'),
    path('relationship/',RelationshipView.as_view(), name='relationship'),
    path('profile/',ProfileListView.as_view(),name='profile'),
    path('profile/update/<int:id>/',ProfileUpdateView.as_view(),name='profile_update'),
    path('profile/delete/<int:id>/',ProfileDeleteView.as_view(),name='profile_delete'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('packages/', PaymentOptionsView.as_view(), name='packages'),    
    path('login/',LoginView.as_view(),name='login'),
    path('change_password/', change_password, name='change_password'),
    path('forgot_password/', forgotpassword, name='forgot_password'),
    path('verify_password/', verify_password, name='verify_password'),


    

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/shared/base.html
<!doctype html>
<html lang="en">

<head>
    {% block meta %}

    {% endblock meta %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS v5.2.1 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />

</head>

<body>
    <header>
        {% include 'shared/navbar.html' %}
    </header>
    <main>
        {% block content %}

        <h1>BASE</h1>

        {% csrf_token %}

        {% endblock content %}
    </main>
    <footer>

        {% include 'shared/footer1.html' %}
    </footer>
    <!-- Bootstrap JavaScript Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>

    {% block scripts %}

    {% endblock scripts %}
</body>

</html>

templates/shared/footer1.html
{% block content %}
<footer class="footer bg-dark mt-5">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="footer_content section">
                    <div class="row g-4 justify-content-center justify-content-xl-between">
                        <div class="col-md-6 col-lg-3">
                            <div class="footer_contact">
                                <h4 class="footer_title text-white mt-0">About Us</h4>
                                <p class="text-white">
                                    In recent years, many singles over 40 have begun to find their feet with dating websites and apps.
                                    There is a whole world of people looking for love, companionship, or friendship. We have gathered, reviewed, and rated the best and most trustworthy sites for you here, to help you on your way!
                                </p>
                            </div>
                        </div>

                        <div class="col-md-6 col-lg-3 col-xl-2">
                            <h4 class="footer_title text-white mt-0">Quick Links</h4>
                            <ul class="footer_contact list list-base list--column">
                                <li class="list-column_item">
                                    <a class="t-link t-link-base text-white d-inline-block" href="{% url 'account:index' %}">Home</a>
                                </li>
                                <li class="list-column_item">
                                    <a class="t-link t-link-base text-white d-inline-block" href="{% url 'account:packages' %}">Packages</a>
                                </li>
                                <li class="list-column_item">
                                    <a class="t-link t-link-base text-white d-inline-block" href="#">Contact Us</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-md-6 col-lg-3 col-xl-2">
                            <h4 class="footer_title text-white mt-0">Policies</h4>
                            <ul class="footer_contact list list-base list--column">
                                <li class="nav-item">
                                    <a class="t-link t-link-base text-white d-inline-block" href="#" target="_blank">Privacy Policy</a>
                                </li>
                                <li class="nav-item">
                                    <a class="t-link t-link-base text-white d-inline-block" href="#" target="_blank">Terms and Conditions</a>
                                </li>
                                <li class="nav-item">
                                    <a class="t-link t-link-base text-white d-inline-block" href="#" target="_blank">Refund and Cancellation Policy</a>
                                </li>
                            </ul>
                        </div>

                        <div class="col-md-6 col-lg-3">
                            <h4 class="footer_title text-white mt-0">Contact Us</h4>
                            <ul class="footer_contact list list-column mt-4">
                                <li>
                                    <i class="fas fa-phone-alt"></i> 
                                    <a class="t-link t-link-base text-white d-inline-block" href="tel:9207735011">9207735011</a>
                                </li>
                                <li>
                                    <i class="far fa-envelope"></i> 
                                    <a class="t-link t-link-base text-white d-inline-block" href="mailto:dating@gmail.com">dating@gmail.com</a>
                                </li>
                                <li class="text-white">
                                    <i class="fas fa-map-marker-alt"></i> Address 
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-12">
                
            </div>
        </div>
    </div>
</footer>
{% endblock content %}

templates/shared/navbar.html
<style>
    * {
        margin: 0;
        padding: 0;
    }

    .nav-link {
        color: white !important;
        font-weight: bold;
    }

    .nav-link:hover {
        color: #5a5f64 !important;
    }

    body {
        background-color: rgb(232, 242, 239);
        font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    }
</style>
<header class="header-bottom">
    <nav class="navbar navbar-light navbar-expand-sm bg-warning nav-link nav-link:hover">
        <div class="container">
            <a class="navbar-brand logo" href="{% url 'account:index' %}">Dating App</a>
            <button class="navbar-toggler header-button collapsed" data-bs-target="#navbarSupportedContent"
                data-bs-toggle="collapse" type="button" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <i class="las la-bars"></i>
            </button>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            {% if user.is_authenticated %}
            <h2> Hi.. {{ user.first_name }}</h2>
            {% endif%}
            <div class="navbar-collapse collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-menu ms-auto">

                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'account:index' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'account:packages' %}">Packages</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link " href="">Contact</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'Dating:gridview' %}">Matches</a>
                    </li>
                    <li class="nav-item ">

                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-2">

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    Profile
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a>
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'Dating:gridview' %}">Dashboard</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'account:change_password' %}">Change password</a></li>
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        </ul>

                    </li>
                    {% endif %}

                    {% if not user.is_authenticated %}
                    <li class="header-login__item nav-item">
                        <a class="btn bg-danger btn--base btn--sm" href="{% url 'account:login' %}"> <i
                                class="las la-user"></i> Login</a>
                    </li>

                    <li class="header-login__item nav-item">
                        <a class="btn bg-light btn--base btn--sm btn--outline" href="{% url 'account:send_otp' %}">
                            Create Account</a>
                    </li>
                </ul>
                {% endif %}

            </div>
        </div>
    </nav>
</header>